services:
  frontend:
    image: frontend:latest
    ports:
      - "5001:5001"
    container_name: frontend_service

  backend:
    image: backend:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    container_name: backend_service
    depends_on:
       - redis
       - db
  redis:
    image: redis:latest
    container_name: redis_service

  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_redmine
