services:
  frontend:
    image: frontend:latest
    restart: unless-stopped
    container_name: frontend_service

  backend:
    image: backend:latest
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    container_name: backend_service
    depends_on:
       - redis
       - db
  redis:
    image: redis:latest
    container_name: redis_service

  db:
    image: postgres:18
    restart: unless-stopped
    volumes:
      - ./_data_:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_redmine

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: proxy
